version: '2.1'

services:
  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
        context: ./web
    volumes:
      - ./web:/usr/src/django
    environment:
      - DJANGO_ADMIN=${DJANGO_ADMIN}
      - DJANGO_ADMIN_PASS=${DJANGO_ADMIN_PASS}
      - APP_DB_ENGINE=${APP_DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      db:
         condition: service_healthy
volumes: 
     pgdata:
