version: '2.1'

services:
  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
        context: ./web
        args:
          test: ${TEST}
    volumes:
      - ./web:/usr/src/django
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      db:
         condition: service_healthy
