version: '3'

services:
  db:
    build: ./db
  web:
    build: .
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; python manage.py migrate; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/usr/src/django
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      - db
