---
- name: Install Java 8
  hosts: all
  become: yes

  tasks:

  - name: Update
    apt: update_cache=yes upgrade=yes

  - name: Install openjdk-8-jre-headless
    apt: name=openjdk-8-jre-headless state=latest

