pipeline {
   
   agent none
   
   stages {
      stage('Install Java') {
         agent { label 'master' }
         steps {
            sh "ansible-playbook ansible/java_install.yml"
         }
      }
      stage('Install Docker') {
         agent { label 'master' }
         steps {       
            sh "ansible-playbook ansible/docker_install.yml"
         }
      }
   }
   post {
      success {
        node('master') {
           build job: 'Opsworks', wait: false
        }
      }
      failure {
        node('master') {
           telegramSend "Job \"${JOB_NAME}\": Build №${BUILD_NUMBER} Failed. More info: ${BUILD_URL}"
         }
      }
   }
}
